### ISSUE TITLE
largeText.txt

### ISSUE THREAD

**Issue by stackupv2** [kevin-wayne/algs4#108]
File largeText.txt  provided on the website [algs4.cs.princeton.edu] is too big,  browse always crashed when I try to open it. Could you please release a download file here?

**Comment by cool-tree** [comment]
you can use the web source code to get the txt file, just click the right click and chose the web source code, then go to the "source" bar, find the largeText.txt, and save it.

**Comment by kevin-wayne** [comment]
You can also right click the link in your browser and save.
