### ISSUE TITLE
Outdated doc comment for BinarySearch

### ISSUE THREAD

**Issue by remcopeereboom** [kevin-wayne/algs4#11]
The class doc comment for `BinarySearch` still references the `rank` operation, but `rank` has been deprecated in favor of `indexOf`.

> The <em>rank</em> operations takes logarithmic time in the worst case.

**Comment by kevin-wayne** [comment]
Thanks, fixed.

> On Jun 19, 2016, at 1:02 AM, Remco Peereboom <notifications@github.com> wrote:
> 
> The class doc comment for BinarySearch still references the rank operation, but rank has been deprecated in favor of indexOf.
> 
> The rank operations takes logarithmic time in the worst case.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
