### ISSUE TITLE
StdDraw.java has a bug in method init() and createMenuBar()

### ISSUE THREAD

**Issue by Melody12ab** [kevin-wayne/algs4#15]
it has errors in init() method
```
draw.addMouseListener(std);
draw.addMouseMotionListener(std);
frame.addKeyListener(std);
```
**_std_** is not the type what the method need.

i use jdk1.8

**Comment by kevin-wayne** [comment]
I think the code is fine, as is. It's been compiled on Java 6, 7, or 8. The variable std of of type StdDraw which implements a variety of interfaces.

public final class StdDraw implements ActionListener, MouseListener, MouseMotionListener, KeyListener {
