### ISSUE TITLE
Is it a mistake inside StdRandom.shuffle

### ISSUE THREAD

**Issue by linbojin** [kevin-wayne/algs4#20]
Hi Kevin,

I am looking at shuffle function inside StdRandom.java, more specifically, the line [520](https://github.com/kevin-wayne/algs4/blob/master/src/main/java/edu/princeton/cs/algs4/StdRandom.java#L520):

```
    /**
     * Rearranges the elements of the specified subarray in uniformly random order.
     *
     * @param  a the array to shuffle
     * @param  lo the left endpoint (inclusive)
     * @param  hi the right endpoint (exclusive)
     * @throws IllegalArgumentException if {@code a} is {@code null}
     * @throws IndexOutOfBoundsException unless {@code (0 <= lo) && (lo < hi) && (hi <= a.length)}
     */
    public static void shuffle(int[] a, int lo, int hi) {
        if (a == null) throw new IllegalArgumentException("argument array is null");
        if (lo < 0 || lo >= hi || hi > a.length) {
            throw new IndexOutOfBoundsException("invalid subarray range: [" + lo + ", " + hi + ")");
        }
        for (int i = lo; i < hi; i++) {
            int r = i + uniform(hi-i+1);     // between i and hi
            int temp = a[i];
            a[i] = a[r];
            a[r] = temp;
        }
    }
```

It is said hi is exclusive so that i think 
```
int r = i + uniform(hi-i+1);     // between i and hi
```
should be
```   
int r = i + uniform(hi-i);     // between i and hi-1
```
because if r equals hi, a[r] may trigger out of IndexOutOfBoundsException. 

Best wishes,
By Linbo

**Comment by kevin-wayne** [comment]
Thanks. Yes, looks like I introduced that bug last month when I made the right endpoint exclusive. Sorry about that. Thanks for bringing to my attention. I’m pushing the change now.

Best,
Kevin

> On Jan 21, 2017, at 2:35 AM, linbo.jin <notifications@github.com> wrote:
> 
> Hi Kevin,
> 
> I am looking at shuffle function inside StdRandom.java, more specifically, the line 520:
> 
>     /**
>      * Rearranges the elements of the specified subarray in uniformly random order.
>      *
>      * @param  a the array to shuffle
>      * @param  lo the left endpoint (inclusive)
>      * @param  hi the right endpoint (exclusive)
>      * @throws IllegalArgumentException if {@code a} is {@code null}
>      * @throws IndexOutOfBoundsException unless {@code (0 <= lo) && (lo < hi) && (hi <= a.length)}
>      */
>     public static void shuffle(int[] a, int lo, int hi) {
>         if (a == null) throw new IllegalArgumentException("argument array is null");
>         if (lo < 0 || lo >= hi || hi > a.length) {
>             throw new IndexOutOfBoundsException("invalid subarray range: [" + lo + ", " + hi + ")");
>         }
>         for (int i = lo; i < hi; i++) {
>             int r = i + uniform(hi-i+1);     // between i and hi
>             int temp = a[i];
>             a[i] = a[r];
>             a[r] = temp;
>         }
>     }
> 
> It is said hi is exclusive so that i think
> 
> int r = i + uniform(hi-i+1);     // between i and hi
> 
> should be
> 
> int r = i + uniform(hi-i);     // between i and hi-1
> 
> because if r equals hi, a[r] may trigger out of IndexOutOfBoundsException.
> 
> Best wishes,
> By Linbo
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by linbojin** [comment]
Fixed in this commit: https://github.com/kevin-wayne/algs4/commit/55fddd7d5da707b34eb8c8a73611bfb312e69864
