### ISSUE TITLE
Maven central 

### ISSUE THREAD

**Issue by nikkekin** [kevin-wayne/algs4#24]
Hey,

Do you have any plans to publish the algorithms in maven central? Would just make the project more usable...

-niklas

**Comment by kevin-wayne** [comment]
It's in bintray. See the link in

https://github.com/kevin-wayne/algs4/blob/master/README.md

Is this what you were looking for?

Best,
Kevin

> On Feb 23, 2017, at 5:32 AM, Nikke <notifications@github.com> wrote:
> 
> Hey,
> 
> Do you have any plans to publish the algorithms in maven central? Would just make the project more usable...
> 
> -niklas
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by nikkekin** [comment]
sorry, my bad :)
