### ISSUE TITLE
Error in GrahamScan

### ISSUE THREAD

**Issue by mpelesh** [kevin-wayne/algs4#27]
Sample points:

1. (1, 1)
2. (0, 0)
3. (0, 5)
4. (5, 0)

Result hull is [(1, 1), (0, 5), (0, 0), (5, 0)] instead of [(0, 0), (5, 0), (0, 5)]

Error caused by `Arrays.sort(points)` in line 73. The class should use `Arrays.sort(a)` - an array created as a part of defensive copy, not an original array that is not used in calculations.

**Comment by kevin-wayne** [comment]
Thanks, fixed. Looks like that bug was just introduced when I changed the argument name to points[].

Best,
Kevin

> On Mar 5, 2017, at 12:44 AM, mpelesh <notifications@github.com> wrote:
> 
> Sample points:
> 
> 	• (1, 1)
> 	• (0, 0)
> 	• (0, 5)
> 	• (5, 0)
> Result hull is [(1, 1), (0, 5), (0, 0), (5, 0)] instead of [(0, 0), (5, 0), (0, 5)]
> 
> Error caused by Arrays.sort(points) in line 73. The class should use Arrays.sort(a) - an array created as a part of defensive copy, not an original array that is not used in calculations.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by mpelesh** [comment]
Fixed
