### ISSUE TITLE
files  words3.txt and tiny.txt do not exist

### ISSUE THREAD

**Issue by ibqn** [kevin-wayne/algs4#29]
Hi, I am struggling to locate files:

 http://algs4.cs.princeton.edu/21sort/words3.txt
 http://algs4.cs.princeton.edu/21sort/tiny.txt

which are mentioned in all sorting algorithms, like for example here:

http://algs4.cs.princeton.edu/21elementary/Selection.java.html

**Comment by kevin-wayne** [comment]
Thanks. Updated the URLs from /21sort/ to /21elementary/.

> On Mar 25, 2017, at 5:24 AM, Evgeny <notifications@github.com> wrote:
> 
> Hi, I am struggling to locate files:
> 
> http://algs4.cs.princeton.edu/21sort/words3.txt
> http://algs4.cs.princeton.edu/21sort/tiny.txt
> 
> which are mentioned in all sorting algorithms, like for example here:
> 
> http://algs4.cs.princeton.edu/21elementary/Selection.java.html
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by marioluan** [comment]
@kevin-wayne This issue may be closed now, right?

**Comment by kevin-wayne** [comment]
Yes, closing.
