### ISSUE TITLE
Some programs missing from the repo

### ISSUE THREAD

**Issue by aishydevil12286** [kevin-wayne/algs4#32]
Hi Kevin,

I found that some of the programs are present as links in the main site, e.g. http://algs4.cs.princeton.edu/33balanced/SplayBST.java.html but these are not present in this repo. Can we please include all such programs also in the repo, to make this as a complete reference. 

Thanks and regards,
Ash

**Comment by kevin-wayne** [comment]
algs4.jar contains all of the programs from 

https://algs4.cs.princeton.edu/code/

You can think of these as the greatest hits. There are hundreds more programs on the booksite.

Some  programs (such as SplayBST.java) would be useful additions to algs4.jar but have not been fully vetted; other programs (such as SortCompare.java) probably have limited usefulness to a wide audience.
