### ISSUE TITLE
Bug In linux instalation instructions

### ISSUE THREAD

**Issue by Ramapitecus** [kevin-wayne/algs4#37]
Hi, in this page http://algs4.cs.princeton.edu/linux/ there is a little bug in the linux instalation instructions. 
This command `sudo chmod 755 checkstyle-{algs4,cos226,algs4}`  should be `sudo chmod 755 checkstyle-{algs4,cos226,coursera}`

Sorry if this is the wrong place to report this, but I didn't find any other place. I'm taking the free coursera mooc.

**Comment by kevin-wayne** [comment]
thanks, fixed

> On Oct 8, 2017, at 11:16 AM, Halim G Naim H <notifications@github.com> wrote:
> 
> Hi, in this page http://algs4.cs.princeton.edu/linux/ there is a little bug in the linux instalation instructions.
> This command sudo chmod 755 checkstyle-{algs4,cos226,algs4} should be sudo chmod 755 checkstyle-{algs4,cos226,coursera}
> 
> Sorry if this is the wrong place to report this, but I didn't find any other place. I'm taking the free coursera mooc.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
