### ISSUE TITLE
a small mistake in StdIn.readAll()

### ISSUE THREAD

**Issue by DuWeiQiang** [kevin-wayne/algs4#38]
the original code in stdin.java
    // used to read the entire input
 223   private static final Pattern EVERYTHING_PATTERN = Pattern.compile("\\A");

but the function stdin.readall() doesn't work.
so i change the pattern to "\\z"
it works.

**Comment by kevin-wayne** [comment]
Can you supply the code and input file that failed? Perhaps your input file is not encoded in UTF-8.

> On Oct 15, 2017, at 4:43 AM, DuWeiQiang <notifications@github.com> wrote:
> 
> the original code in stdin.java
> // used to read the entire input
> 223 private static final Pattern EVERYTHING_PATTERN = Pattern.compile("\A");
> 
> but the function stdin.readall() doesn't work.
> so i change the pattern to "\z"
> it works.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by DuWeiQiang** [comment]
**the test code like this**
`import java.util.Scanner;
import java.util.regex.Pattern;

import edu.princeton.cs.algs4.*;

public class Test {
	public static void main(String[] args) {
		StdOut.print(StdIn.readAll());
	}
}
`
there is no input file.i input the data in command line,
run this code,and type any strings like "sadcnwe5s4484wfare" then press enter, nothing display.
and fix code like this 
`
public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
		StdOut.print(scanner.useDelimiter(Pattern.compile("\\z")).next());
}
`
type any strings then press enter,it'll display what i just type
thanks for your answer

**Comment by kevin-wayne** [comment]
If you are not redirecting standard input from a file, you must explicitly signal that you are done by entering the end-of-file sequence, typically Ctrl-D or Ctrl-Z on its own line.


> On Oct 17, 2017, at 11:12 PM, DuWeiQiang <notifications@github.com> wrote:
> 
> the test code like this
> `import java.util.Scanner;
> import java.util.regex.Pattern;
> 
> import edu.princeton.cs.algs4.*;
> 
> public class Test {
> public static void main(String[] args) {
> StdOut.print(StdIn.readAll());
> }
> }
> there is no input file.i input the data in command line, run this code,and type any strings like "sadcnwe5s4484wfare" then press enter, nothing display. and fix code like this
> public static void main(String[] args) {
> Scanner scanner = new Scanner(System.in);
> StdOut.print(scanner.useDelimiter(Pattern.compile("\z")).next());
> }
> `
> type any strings then press enter,it'll display what i just type
> thanks for your answer
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
