### ISSUE TITLE
can't find 1Mints.txt

### ISSUE THREAD

**Issue by WenHaiGo** [kevin-wayne/algs4#39]
I downloaded the  algs4-data.zip from https://algs4.cs.princeton.edu/code/, but I did not find the 1Mints.txt. help~~

**Comment by WenHaiGo** [comment]
16Kints.txt  and 32Kints.txt  are also not found.

**Comment by kevin-wayne** [comment]
Thanks, fixed.

> On Oct 26, 2017, at 11:33 PM, WenHaiGo <notifications@github.com> wrote:
> 
> 16Kints.txt and 32Kints.txt are also not found.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
