### ISSUE TITLE
Is there a bug in BST.java?

### ISSUE THREAD

**Issue by Oliver-Ren** [kevin-wayne/algs4#4]
I am just wondering is this a bug or not for the BST.java:

At the line 147, the comments said "@throws NullPointerException if <tt>key</tt> is <tt>null</tt>".  But it is possible to use the public void put(Key key, Value val) method to put __null__ key when the root of the tree is still __null__ without throwing any exceptions. 

But later operations on the BST such as get, delete etc. will throw NullPointerException because we have constructed a root node with null key.

**Comment by kevin-wayne** [comment]
Thanks, yes I’ve just added explicit checks for null keys to various symbol table methods. (It looks like ST.java had them, but not several of the other symbol table implementations.) Thanks again for bringing to our attention.

Best,
Kevin

> On Nov 20, 2015, at 3:04 AM, Chengxiang Ren <notifications@github.com> wrote:
> 
> I am just wondering is this a bug or not for the BST.java:
> 
> At the line 147, the comments said "@throws NullPointerException if key is null". But it is possible to use the public void put(Key key, Value val) method to put null key when the root of the tree is still null without throwing any exceptions.
> 
> But later operations on the BST such as get, delete etc. will throw NullPointerException because we have constructed a root node with null key.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
