### ISSUE TITLE
What is the so called whitelist in exercise 1.1.23?

### ISSUE THREAD

**Issue by eduOS** [kevin-wayne/algs4#42]
I am confused on what the whitelist is.. 

Please point me in the right direction on that exercise, thanks very much.

**Comment by IvanMwiruki** [comment]
From page 48

> Whitelisting. When possible, our development clients are intended to mirror practical
situations and demonstrate the need for the algorithm at hand. In this case, the process
is known as whitelisting. Specifically, imagine a credit card company that needs to check
whether customer transactions are for a valid account. To do so, it can
■ Keep customers account numbers in a file, which we refer to as a whitelist.
■ Produce the account number associated with each transaction in the standard
input stream.
■ Use the test client to put onto standard output the numbers that are not associated
with any customer. Presumably the company would refuse such transactions.
It would not be unusual for a big company with millions of customers to have to process
millions of transactions or more. To model this situation, we provide on the booksite
the files largeW.txt (1 million integers) and largeT.txt (10 million integers).
Performance. A working program is often not sufficient. For example, a much simpler 

Also see page 47
