### ISSUE TITLE
[improvement] EdgeWeightedDigraph search for paths by number of nodes or 

### ISSUE THREAD

**Issue by archenroot** [kevin-wayne/algs4#46]
First of all thanks for this work, brilliant piece for learning curve in not only graph theory. I had an idea to improve EdgeWeightedDigraph class by obtaining Paths by:
- number of nodes in path: can be equalTo, GT, G, LT, L types
- node or node list

What do you think?

**Comment by kevin-wayne** [comment]
Not actually sure what you are proposing. What would be the extra methods in the EdgeWeightedDigraph API? For which applications would this be a useful expansion of the API? Would it be possible to have a stand-alone adapter class that achieves the same functionality (in an efficient manner) without changing the EdgeWeightedDigraph API?

> On Feb 15, 2018, at 7:16 AM, archenroot <notifications@github.com> wrote:
> 
> First of all thanks for this work, brilliant piece for learning curve in not only graph theory. I had an idea to improve EdgeWeightedDigraph class by obtaining result filtered by:
> 
> 	• number of nodes in path: can be equalTo, GT, G, LT, L types
> 	• node or node list
> What do you think?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by archenroot** [comment]
@kevin-wayne - you are right, I already did api wrapper which does this for me. Let leave the algorithm in its pure form. Thx for comment.
