### ISSUE TITLE
Can't figure out exercise 2.3.11

### ISSUE THREAD

**Issue by Ninzero** [kevin-wayne/algs4#56]
I just can't imagine a situation that will change the time complexity of quick sort to O(n^2) when we change the stopping condition for scanning smaller than a[lo] instead of smaller or equal than a[lo]. And I can not find any answers on the internet.

**Comment by kjosib** [comment]
If a vector contains many copies of the same value, you would rather recognize them as sorted in one swell foop.

**Comment by kevin-wayne** [comment]
Unrelated to algs4.jar repo.
