### ISSUE TITLE
One edge is enough for self loop edges

### ISSUE THREAD

**Issue by yaojingguo** [kevin-wayne/algs4#59]
Both [EulerianPath.java](https://github.com/kevin-wayne/algs4/blob/master/src/main/java/edu/princeton/cs/algs4/EulerianPath.java) and [EulerianCycle.java](https://github.com/kevin-wayne/algs4/blob/master/src/main/java/edu/princeton/cs/algs4/EulerianCycle.java) have the self-loop handling code:
```Java
                // careful with self loops
                if (v == w) {
                    if (selfLoops % 2 == 0) {
                        Edge e = new Edge(v, w);
                        adj[v].enqueue(e);
                        adj[w].enqueue(e);
                    }
                    selfLoops++;
                }
```

Since an edge can only be used once, ` adj[w].enqueue(e);` can be safely removed.

**Comment by kevin-wayne** [comment]
The graph theory convention is to include two copies of each self loop. For example, this is needed to ensure that the sum of the degrees of the vertices in an undirected graph is even.

**Comment by yaojingguo** [comment]
OK
