### ISSUE TITLE
Publish algs4.jar to jCenter or maven centrual repositray

### ISSUE THREAD

**Issue by weijianwen** [kevin-wayne/algs4#6]
Hi,

Is there any plan to publish algs4.jar to [jCenter](https://bintray.com/bintray/jcenter) or [Maven](http://search.maven.org) repositrary? It will benefit the users who specify depency for algs4 library in the build file.

**Comment by kevin-wayne** [comment]
> Hi,
> 
> Is there any plan to publish algs4.jar to jCenter or Maven repositrary? It will benefit the users who specify depency for algs4 library in the build file.

There was no current plan, primarily because I don’t use Maven and didn’t know that would be useful. (A student added the Maven and Gradle support.) Could you let me know what would be the process for (1) initiating a Maven repository and (2) updating the repository whenever algs4.jar changes?

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by weijianwen** [comment]
Sure thing. Publishing java libraries to the public repository provides a reliable way to retrieve verified libs among various versions. Combined with Java auto build tools like [Maven](http://search.maven.org) or [gradle](http://gradle.org), java libs along with its dependency can be downloaded automatically.

@slok hosts an unofficial Maven repository in [algs4-mvn-repo](https://github.com/slok/algs4-mvn-repo/). It works well in my algs4 programming assignments.

Both [jCenter](https://bintray.com/bintray/jcenter) and [Maven Central](http://search.maven.org) are *maven-compatible* repositories, whcih can work with gradle and maven. jCenter is preferred since it is bigger, more friendly to end users and can be deployed to Maven with ease.

To publish a java lib to jCenter, you need to

1. Register [Bintray](https://bintray.com);
2. Add algs4 to Bintray's Maven repository;
3. Optionally, register a [Sonatype](https://sonatype.org) account, then deploy algs4 to Maven Central repo from the Bintray site.

You may refer this blog for more information: http://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en .

**Comment by weijianwen** [comment]
Bintray team provides code snippets for publishing libs to jCenter and Maven via gradle. I can help to do some tests.

* https://github.com/bintray/bintray-examples/tree/master/gradle-example
* https://github.com/bintray/bintray-examples/blob/master/maven-example/multi3/pom.xml

**Comment by greyby** [comment]
@weijianwen  The package had uploaded to jCenter. The home page is [algs4](https://bintray.com/algs4/maven/algs4). You can add depencency with gradle or maven.

**Comment by slok** [comment]
Thank you! :D I will link there in the README and set this as a deprecated repository.

**Comment by sgluschenko** [comment]
@weijianwen can this issue be closed? :)

**Comment by weijianwen** [comment]
Sure. :-)
