### ISSUE TITLE
regarding "unit testing": suggest move to JUnit or TestNG rather than main method invocation

### ISSUE THREAD

**Issue by ny83427** [kevin-wayne/algs4#64]
Currently, in assignments and source code, tests are made via calling methods in the main method, this require the user to check input, output manually and is not that efficient.

I highly recommend that those unit tests can be written in JUnit or TestNG, which is more close to the meaning of unit tests, while providing convenience to students who are doing programming assignments.

PS: I just enrolled `algorithms-part1` at coursera and it's awesome. Thank you for providing such a great online free course.

For example, for the percolation I just finished, suppose we prepare test cases like this(you can use them freely and correct if I made some mistake. It spent me some time man):
```
greeting57.txt,2522,false
heart25.txt,352,false
input1-no.txt,0,false
input1.txt,1,true
input10-no.txt,55,false
input10.txt,56,true
input2-no.txt,2,false
input2.txt,3,true
input20.txt,250,true
input3.txt,6,true
input4.txt,8,true
input5.txt,25,true
input50.txt,1412,true
input6.txt,18,true
input7.txt,16,true
input8-dups.txt,34,true
input8-no.txt,33,false
input8.txt,34,true
java60.txt,578,true
jerry47.txt,1476,true
sedgewick60.txt,2408,true
snake101.txt,5101,true
snake13.txt,85,true
wayne98.txt,5079,true
```

And I wrote unit test like this, which is helpful while I improve my coding to meet the grade requirement:

```java
    @Test
    public void runAll() {
        In in = new In(this.getClass().getResource("/percolation-test-cases.txt"));
        int failed = 0;
        while (!in.isEmpty()) {
            String line = in.readLine();
            String[] array = line.split(",");
            Percolation perc = this.from(array[0]);

            try {
                assertEquals(perc.numberOfOpenSites(), Integer.parseInt(array[1]));
                assertEquals(perc.percolates(), Boolean.parseBoolean(array[2]));
            } catch (AssertionError e) {
                System.err.println(line + " -> " + perc.numberOfOpenSites() + "," + perc.percolates());
                failed++;
            }
        }

        if (failed > 0) {
            throw new AssertionError(failed + " test cases failed!");
        }
    }

    @Test
    public void isFull() {
        Percolation perc = new Percolation(3);
        perc.open(1, 1);
        perc.open(3, 1);
        assertFalse(perc.isFull(3, 1));

        perc.open(1, 3);
        perc.open(3, 3);
        assertFalse(perc.isFull(3, 3));

        perc.open(2, 3);
        assertTrue(perc.isFull(3, 3));
        assertFalse(perc.isFull(3, 1));
    }
```

**Comment by ny83427** [comment]
PS: Some helper test methods are here.

```java
    @AllArgsConstructor
    private static class FullCheckPoint {
        private int openCount;
        private int row, column;
        private boolean expectedFullStatus;
    }

    private Percolation from(String textFile, FullCheckPoint... checkPoints) {
        In in = new In(this.getClass().getResource("/percolation/" + textFile));
        Percolation perc = new Percolation(in.readInt());
        while (!in.isEmpty()) {
            int row = in.readInt();
            int col = in.readInt();
            perc.open(row, col);

            if (checkPoints == null || checkPoints.length == 0) continue;
            for (FullCheckPoint p : checkPoints) {
                if (perc.numberOfOpenSites() == p.openCount &&
                    perc.isFull(p.row, p.column) != p.expectedFullStatus) {
                    throw new AssertionError(String.format("%s: %d sites opened, (%d, %d) full status different from" +
                        " expected status %s", textFile, p.openCount, p.row, p.column, p.expectedFullStatus));
                }
            }
        }
        return perc;
    }
```

**Comment by danielpacak** [comment]
Glad to see such proposal. JUnit is somehow industry standard for professional Java programmers. If you mix with powerful assertion library such as AssertJ the tests look amazing.

**Comment by ny83427** [comment]
> Glad to see such proposal. JUnit is somehow industry standard for professional Java programmers. If you mix with powerful assertion library such as AssertJ the tests look amazing.

Hey dude, thanks for your recommendation of AssertJ, would have a try then?

**Comment by beaunus** [comment]
I suspect that one of the goals of this repository is to be _easily accessible_ to beginners. Perhaps the professors' choice to use the `main` methods for testing is better for their target audience as educators.

However, I agree that the proposal for formal automated testing is worth consideration. What does professor @kevin-wayne think of the idea?

If the professor is willing to consider allowing automated tests to make it into the repository, we (the community) could prepare some PRs with examples of what we have in mind. Then, after review, we could agree on a suitable course of action.

If the professor prefers not to proceed with unit tests, perhaps we should close this issue.

**Comment by ny83427** [comment]
More than one year passed, I'd like to close this issue as it looks like that Professor Wayne would not proceed with Unit Tests.

Thanks for your comments and interests.
