### ISSUE TITLE
Inconsistent size() with TST deletion using the put method

### ISSUE THREAD

**Issue by fakeProgrammer0** [kevin-wayne/algs4#73]
As suggested by the api contract of put in [TST.java](https://github.com/kevin-wayne/algs4/blob/master/src/main/java/edu/princeton/cs/algs4/TST.java),

> If the value is {@code null}, this effectively deletes the key from the symbol table.

However, when calling the put method with null value to delete an exisiting key, the size of the symbol table doesn't decrement by one. Instead, the size just remains the same, which is inconsistent with the number of keys fetched by the orderkeys() method.

```java
public void put(String key, Value val) {
    if (key == null) {
        throw new IllegalArgumentException("calls put() with null key");
    }
    if (!contains(key)) n++;
    root = put(root, key, val, 0);
}
```

Below is a simple test routine.

```java
@Test
void testTSTDelete()
{
    // The whole test routine passes, but something is wrong...
    
    TST<Integer> tst = new TST<>();
    tst.put("a", 1);
    tst.put("b", 2);
    tst.put("c", 3);
    assertEquals(3, tst.size());
    
    /*
    call the put method with null value to remove b from the TST, as suggested by the
    api contract "If the value is {@code null}, this effectively deletes the key from the symbol table."
     */
    tst.put("b", null);
    
    // expected tst.size() == 2, but was 3
    assertEquals(3, tst.size());
    assertNull(tst.get("b"));
    
    int cnt = 0;
    for (String key : tst.keys())
    {
        cnt++;
        assertNotEquals("b", key);
        System.out.print(key + " ");
    }
    // only get 2 keys, inconsistent with tst.size() == 3
    assertEquals(2, cnt);
}
```

Here's a piece of advice. Just add one line to decrement the size by one to fix the inconsistency : )

```java
public void put(String key, Value val) {
    if (key == null) {
        throw new IllegalArgumentException("calls put() with null key");
    }

    if (!contains(key)) n++;
    else if(val == null) n--; // delete existing key

    root = put(root, key, val, 0);
}
```

**Comment by kevin-wayne** [comment]
Thanks, good catch. I’ve pushed the proposed change.

> On Aug 4, 2019, at 7:51 AM, fakeProgrammer0 <notifications@github.com> wrote:
> 
> As suggested by the api contract of put,
> 
> If the value is {@code null}, this effectively deletes the key from the symbol table.
> 
> However, when calling the put method with null value to delete an exisiting key, the size of the symbol table doesn't decrement by one. Instead, the size just remains the same, which is inconsistent with the number of keys fetched by the orderkeys() method.
> 
> public void put(String key, Value
>  val) {
>     
> if (key == null
> ) {
>         
> throw new IllegalArgumentException("calls put() with null key"
> );
>     }
>     
> if (!contains(key)) n++
> ;
>     root 
> = put(root, key, val, 0
> );
> }
> 
> Below is a simple test routine.
> 
> @Test
> void
>  testTSTDelete()
> {
>     
> // The whole test routine passes, but something is wrong...
> 
>     
>     
> TST<Integer> tst = new TST<>
> ();
>     tst
> .put("a", 1
> );
>     tst
> .put("b", 2
> );
>     tst
> .put("c", 3
> );
>     assertEquals(
> 3, tst.
> size());
>     
>     
> /*
>     call the put method with null value to remove b from the TST, as suggested by the
>     api contract "If the value is {@code null}, this effectively deletes the key from the symbol table."
>      */
> 
>     tst
> .put("b", null
> );
>     
>     
> // expected tst.size() == 2, but was 3
> 
>     assertEquals(
> 3, tst.
> size());
>     assertNull(tst
> .get("b"
> ));
>     
>     
> int cnt = 0
> ;
>     
> for (String key : tst.
> keys())
>     {
>         cnt
> ++
> ;
>         assertNotEquals(
> "b"
> , key);
>         
> System.out.print(key + " "
> );
>     }
>     
> // only get 2 keys, inconsistent with tst.size() == 3
> 
>     assertEquals(
> 2
> , cnt);
> }
> 
> Here's a piece of advice. Just add one line to decrement the size by one to fix the inconsistency : )
> 
> public void put(String key, Value
>  val) {
>     
> if (key == null
> ) {
>         
> throw new IllegalArgumentException("calls put() with null key"
> );
>     }
> 
>     
> if (!contains(key)) n++
> ;
>     
> else if(val == null) n--; // delete existing key
> 
> 
>     root 
> = put(root, key, val, 0
> );
> }
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by fakeProgrammer0** [comment]
Thx for reply : )
