### ISSUE TITLE
Typo in comment: a tournament is not a DAG

### ISSUE THREAD

**Issue by michaelcadilhac** [kevin-wayne/algs4#75]
https://github.com/kevin-wayne/algs4/blob/97bddfb06195bf76c3fe05f08ad122f4b6d8068d/src/main/java/edu/princeton/cs/algs4/DigraphGenerator.java#L141-L143

Thanks!
Michaël

**Comment by kevin-wayne** [comment]
thanks, fixed error in comment

> On Nov 5, 2019, at 6:56 PM, Michaël Cadilhac <notifications@github.com> wrote:
> 
> https://github.com/kevin-wayne/algs4/blob/97bddfb06195bf76c3fe05f08ad122f4b6d8068d/src/main/java/edu/princeton/cs/algs4/DigraphGenerator.java#L141-L143
> 
> Thanks!
> Michaël
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
