### ISSUE TITLE
`StdRandom::geometric(double p)` allows casting Infinity to an int

### ISSUE THREAD

**Issue by remcopeereboom** [kevin-wayne/algs4#8]
`StdRandom::geometric(double p)` allows casting Infinity to an int.
The potential issue occurs when `p = 1.0`. This may or may not be what you want, but it seems dicey even if the maximum integer is the closest approximation.

**Comment by kevin-wayne** [comment]
Thanks. Returning Integer.MAX_VALUE seems to be the most reasonable behavior if p is (nearly) equal to 1.0. I will make a note to document this corner case in the Javadoc. 


> On Mar 18, 2016, at 6:46 AM, Remco Peereboom <notifications@github.com> wrote:
> 
> StdRandom::geometric(double p) allows casting Infinity to an int.
> The potential issue occurs when p = 1.0. This may or may not be what you want, but it seems dicey even if the maximum integer is the closest approximation.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University

**Comment by remcopeereboom** [comment]
Thanks. I assumed that to be the case. It came up in ruby where the choice isn't quite as trivial: big integers can grow arbitrarily large and it's not possible to cast Float::Infinity to an integer.
