### ISSUE TITLE
EdgeWeightedDigraph.java wrong data file url

### ISSUE THREAD

**Issue by webberpuma** [kevin-wayne/algs4#80]
in the top comment section of `EdgeWeightedDigraph.java`, the url of data files are wrong.

for example, `https://algs4.cs.princeton.edu/44st/tinyEWD.txt` will lead to `file not found` page
the correct url, after a google search, turns out to be `https://algs4.cs.princeton.edu/44sp/tinyEWD.txt`

so `44st` should be changed to `44sp` in the url

**Comment by kevin-wayne** [comment]
Thanks, fixed.
