### ISSUE TITLE
Rename parameters for intervals.

### ISSUE THREAD

**Issue by remcopeereboom** [kevin-wayne/algs4#9]
For 1D and 2D-Intervals, I suggest renaming xleft/xright/yleft/yright to xmin/xmax/ymin/ymax respectively.
The former terms are suggestive of a particular coordinate system, while the latter terms are not.

**Comment by kevin-wayne** [comment]
Hi Remco. Thanks, I agree. I’ve updated Interval1D and Interval2D to use min/max names (and deprecated the left() and right() methods).


> On Mar 18, 2016, at 7:23 AM, Remco Peereboom <notifications@github.com> wrote:
> 
> For 1D and 2D-Intervals, I suggest renaming xleft/xright/yleft/yright to xmin/xmax/ymin/ymax respectively.
> The former terms are suggestive of a particular coordinate system, while the latter terms are not.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Kevin Wayne
Phillip Y. Goldman '86 Senior Lecturer
Department of Computer Science
Princeton University
